// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ClubManagementSystem.Repository.Entities;
using Microsoft.EntityFrameworkCore;

namespace ClubManagementSystem.Repository.DBContext;

public partial class ClubManagementSystemContext : DbContext
{
    public ClubManagementSystemContext(DbContextOptions<ClubManagementSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<ApplyRegistration> ApplyRegistrations { get; set; }

    public virtual DbSet<Club> Clubs { get; set; }

    public virtual DbSet<ClubMembership> ClubMemberships { get; set; }

    public virtual DbSet<Deparment> Deparments { get; set; }

    public virtual DbSet<Registration> Registrations { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Accounts__3214EC07B3615E69");

            entity.HasIndex(e => e.Email, "UQ_Accounts_Email").IsUnique();

            entity.HasIndex(e => e.Username, "UQ_Accounts_Username").IsUnique();

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ApplyRegistration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ApplyReg__3214EC07D221C71B");

            entity.ToTable("ApplyRegistration");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Registration).WithMany(p => p.ApplyRegistrations)
                .HasForeignKey(d => d.RegistrationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ApplyRegistration_Registration");

            entity.HasOne(d => d.Student).WithMany(p => p.ApplyRegistrations)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ApplyRegistration_Student");
        });

        modelBuilder.Entity<Club>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Club__3214EC0712219E85");

            entity.ToTable("Club");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Description).IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Deparment).WithMany(p => p.Clubs)
                .HasForeignKey(d => d.DeparmentId)
                .HasConstraintName("FK_Club_Deparment");
        });

        modelBuilder.Entity<ClubMembership>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ClubMemb__3214EC07F7176B7A");

            entity.ToTable("ClubMembership");

            entity.Property(e => e.ApprovedAt).HasColumnType("datetime");
            entity.Property(e => e.ClubRole)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Note)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.RequestedAt).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ApprovedByNavigation).WithMany(p => p.ClubMemberships)
                .HasForeignKey(d => d.ApprovedBy)
                .HasConstraintName("FK_ClubMembership_Accounts");

            entity.HasOne(d => d.Club).WithMany(p => p.ClubMemberships)
                .HasForeignKey(d => d.ClubId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClubMembership_Club");

            entity.HasOne(d => d.Student).WithMany(p => p.ClubMemberships)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClubMembership_Student");
        });

        modelBuilder.Entity<Deparment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Deparmen__3214EC07A744F5C7");

            entity.ToTable("Deparment");

            entity.HasIndex(e => e.Name, "UQ_Deparment_Name").IsUnique();

            entity.Property(e => e.CodeName)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Registration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Registra__3214EC07BFDB9AAB");

            entity.ToTable("Registration");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.EndDay).HasColumnType("datetime");
            entity.Property(e => e.Note)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.StartDay).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Club).WithMany(p => p.Registrations)
                .HasForeignKey(d => d.ClubId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Registration_Club");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Student__3214EC076BAA4953");

            entity.ToTable("Student");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Account).WithMany(p => p.Students)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Student_Accounts");

            entity.HasOne(d => d.Deparment).WithMany(p => p.Students)
                .HasForeignKey(d => d.DeparmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Student_Deparment");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}