// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClubManagementSystem.Repository.Entities;

public partial class ApplyRegistration
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public int RegistrationId { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Registration Registration { get; set; }

    public virtual Student Student { get; set; }
}