// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClubManagementSystem.Repository.Entities;

public partial class Club
{
    public int Id { get; set; }

    public int? DeparmentId { get; set; }

    public string Name { get; set; }

    public bool? IsPublic { get; set; }

    public string Description { get; set; }

    public DateOnly? EstablishedDate { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<ClubMembership> ClubMemberships { get; set; } = new List<ClubMembership>();

    public virtual Deparment Deparment { get; set; }

    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();
}