// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClubManagementSystem.Repository.Entities;

public partial class ClubMembership
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public int ClubId { get; set; }

    public string ClubRole { get; set; }

    public string Status { get; set; }

    public DateTime? RequestedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public int? ApprovedBy { get; set; }

    public string Note { get; set; }

    public virtual Account ApprovedByNavigation { get; set; }

    public virtual Club Club { get; set; }

    public virtual Student Student { get; set; }
}