// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClubManagementSystem.Repository.Entities;

public partial class Registration
{
    public int Id { get; set; }

    public int ClubId { get; set; }

    public DateTime? StartDay { get; set; }

    public DateTime? EndDay { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<ApplyRegistration> ApplyRegistrations { get; set; } = new List<ApplyRegistration>();

    public virtual Club Club { get; set; }
}