// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClubManagementSystem.Repository.Entities;

public partial class Student
{
    public int Id { get; set; }

    public int AccountId { get; set; }

    public int DeparmentId { get; set; }

    public string Status { get; set; }

    public string Code { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<ApplyRegistration> ApplyRegistrations { get; set; } = new List<ApplyRegistration>();

    public virtual ICollection<ClubMembership> ClubMemberships { get; set; } = new List<ClubMembership>();

    public virtual Deparment Deparment { get; set; }
}